### ISSUE TITLE
Request for the LLaVA-Description dataset

### ISSUE THREAD

**Issue by jameslahm** [liuzuyan/ElasticCache#3]
Thanks for your great work! Would you mind sharing the LLaVA-Description dataset? Thanks a lot.

**Comment by liuzuyan** [comment]
Thanks for the interest! You can get access to our random choose LLaVA-Description dataset [here](https://drive.google.com/file/d/1_I2sokdpv8hLzLUe8UUmFvihbh6Kmytv/view?usp=sharing)
